import discord
from discord import app_commands
from discord.ext import commands
import os
import datetime
import asyncio
import json
from collections import deque
from dotenv import load_dotenv

# Runtime package installer helper
import importlib
import subprocess
import sys
import time

# --- Runtime Installer for google-generativeai ---
AI_AVAILABLE = False
genai = None
GenerationConfig = None
APIError = Exception

PYPI_PACKAGE_NAME = "google-generativeai"  # Correct package name

def try_runtime_install(package_name: str) -> bool:
    """
    Installs a package at runtime. Returns True if successful.
    """
    try:
        # Upgrade pip first to avoid installation issues
        subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "pip"], check=True)
        # Install the package
        subprocess.run([sys.executable, "-m", "pip", "install", "--no-cache-dir", package_name], check=True)
        importlib.invalidate_caches()
        print(f"✅ Successfully installed {package_name}.")
        return True
    except Exception as e:
        print(f"❌ Failed to install {package_name}: {e}")
        return False

# Try to import, fallback to runtime install if missing
try:
    import google.generativeai as genai
    from google.generativeai.types import GenerationConfig
    from google.generativeai.errors import APIError
    AI_AVAILABLE = True
except ModuleNotFoundError:
    print(f"⚠️ {PYPI_PACKAGE_NAME} not installed, attempting runtime install...")
    if try_runtime_install(PYPI_PACKAGE_NAME):
        try:
            import google.generativeai as genai
            from google.generativeai.types import GenerationConfig
            from google.generativeai.errors import APIError
            AI_AVAILABLE = True
        except Exception as e:
            print(f"❌ Failed to import {PYPI_PACKAGE_NAME} after install: {e}")

if not AI_AVAILABLE:
    print("❌ AI features are disabled for this run. The bot will start, but AI commands won't work.")

# --- Load Environment Variables ---
load_dotenv()
DISCORD_TOKEN = os.environ.get("DISCORD_TOKEN")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
GEMINI_MODEL = "gemini-2.5-flash"

# --- Configure Gemini Client if Available ---
if AI_AVAILABLE and GEMINI_API_KEY:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        print(f"✅ Gemini client configured with {GEMINI_MODEL}.")
    except Exception as e:
        print(f"❌ Failed to configure Gemini client: {e}")
else:
    if not AI_AVAILABLE:
        print("❌ GEMINI client library missing: AI features are disabled.")
    elif not GEMINI_API_KEY:
        print("❌ GEMINI_API_KEY not found: AI features are disabled.")

# --- Discord Bot Setup ---
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix="!", intents=intents)

# --- Bot Feature Variables ---
VERIFY_ROLE_NAME = "🧑︱Member"
COMMANDS_DATA_FILE = "commands_data.json"
TICKETS_DATA_FILE = "tickets_data.json"
TICKET_CATEGORY_NAME = "Tickets"

AI_SYSTEM_INSTRUCTION = (
    "You are an engaging, detailed, and creative assistant. "
    "Your response must *always* be presented as a single, comprehensive paragraph or summary. "
    "Crucially, you must heavily incorporate relevant and descriptive emojis throughout the text "
    "to make the message visually appealing and expressive. "
    "Do not include any prefaces, attribution, or headers like 'AI generated', 'Generated by User', or 'Here is your summary'."
)

# --- Gemini API Helper Function ---
async def chat_with_ai(messages: list):
    if not AI_AVAILABLE:
        return "Sorry, AI features are currently disabled on this deployment (missing package). 🤖"

    if not GEMINI_API_KEY:
        return "Sorry, AI features are currently disabled due to a missing GEMINI_API_KEY. 🔒"

    config = GenerationConfig(system_instruction=AI_SYSTEM_INSTRUCTION)

    try:
        response = await asyncio.to_thread(
            genai.client.models.generate_content,
            model=GEMINI_MODEL,
            contents=messages,
            config=config,
        )

        if getattr(response, "text", None):
            return response.text
        elif getattr(response, "candidates", None) and response.candidates:
            candidate = response.candidates[0]
            if getattr(candidate, "safety_ratings", None):
                return "🛡️ Your request was blocked due to safety concerns. Please try a different query. 🚫"
            return getattr(candidate, "content", "🤖 The AI returned an unexpected response.")
        else:
            return "🤖 I received an empty or malformed response from the AI. Please try again. 🛠️"

    except APIError as e:
        print(f"Gemini API Error: {e}")
        return f"🚨 I ran into an issue communicating with the AI model: {e} 💔"
    except Exception as e:
        print(f"General AI Error: {e}")
        return f"Oops! An unexpected error occurred while processing your request: {e} 🐛"

# --- Discord Event Handlers ---
@bot.event
async def on_ready():
    print(f'✨ Logged in as {bot.user} (ID: {bot.user.id})')
    try:
        synced = await bot.tree.sync()
        print(f"🤖 Synced {len(synced)} command(s) globally.")
    except Exception as e:
        print(f"❌ Failed to sync commands on ready: {e}")

# --- Bot Runner ---
if not DISCORD_TOKEN:
    print("FATAL ERROR: DISCORD_TOKEN environment variable is not set. The bot cannot start.")
else:
    try:
        bot.run(DISCORD_TOKEN)
    except discord.errors.LoginFailure:
        print("FATAL ERROR: Invalid Discord token provided. Please check your DISCORD_TOKEN.")
    except Exception as e:
        print(f"An unexpected error occurred during bot execution: {e}")
